// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wengeyaumojmalxiteum.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndlbmdleWF1bW9qbWFseGl0ZXVtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUyMzU1MjEsImV4cCI6MjA3MDgxMTUyMX0.Tw5ch7bjaL0FVK2sjSm4BtSfUMfb7eFevM0HWUU55PY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});